name: Deploy

on:
  workflow_call:
    inputs:
      stage:
        type: string
        required: true
    secrets:
      aws-access-key-id:
        required: true
      aws-access-key-secret:
        required: true
      aws-cloudfront-distribution-id:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build -- --configuration ${{ inputs.stage }}

      - name: AWS Sync
        run: |
          aws s3 sync --no-progress --delete dist/frontend s3://atisot-admin-frontend-${{ inputs.stage }}
          aws s3 cp release-control.html s3://atisot-admin-frontend-${{ inputs.stage }}/release-control.html
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-access-key-secret }}
          AWS_DEFAULT_REGION: eu-central-1

      - name: AWS Cache Invalidation
        run: aws cloudfront create-invalidation --paths "/*" --distribution-id ${{ secrets.aws-cloudfront-distribution-id }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-access-key-secret }}
          AWS_DEFAULT_REGION: eu-central-1
