name: Deploy STAGE

on:
  workflow_run:
    workflows: ['Create Pre-Release']
    branches: [main]
    types: [completed]

  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      stage: stage
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_STAGE }}
      aws-access-key-secret: ${{ secrets.AWS_ACCESS_KEY_SECRET_STAGE }}
      aws-cloudfront-distribution-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_STAGE }}
